#!/usr/bin/env python3
"""Count the "AI usage" answers in the pull requests of a JupyterLab release.

Usage: python3 tools/ai_usage.py [version]     (default 4.6.0)

Reads the PR list of the release from ~/jupyterlab/CHANGELOG.md (the x.y.0
entry is cumulative since the previous minor release), fetches each PR with
`gh api graphql`, and parses the first bullet of the "AI usage" section that
the PR template gained on 2026-02-13 (jupyterlab/jupyterlab#18413):

    - **YES**: Some or all of the content of this PR was generated by AI.

Writes sources/release-stats/prs-<version>.json and prints a summary.
"""

import json
import pathlib
import re
import subprocess
import sys
from collections import Counter

VERSION = sys.argv[1] if len(sys.argv) > 1 else "4.6.0"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "sources" / "release-stats"
CHANGELOG = pathlib.Path.home() / "jupyterlab" / "CHANGELOG.md"
TEMPLATE_DATE = "2026-02-13"


def changelog_prs(version):
    lines = CHANGELOG.read_text().split("\n")
    start = lines.index(f"## {version}")
    end = next(i for i in range(start + 1, len(lines)) if lines[i].startswith("## "))
    prs, category = [], None
    for line in lines[start:end]:
        if line.startswith("### "):
            category = line[4:].strip()
        elif category and line.startswith("- "):
            m = re.search(r"\[#(\d+)\]\(https://github.com/jupyterlab/jupyterlab/pull/\d+\)", line)
            if m:
                prs.append({"number": int(m.group(1)), "category": category})
    return prs


def fetch(numbers):
    fields = "number title createdAt mergedAt baseRefName author { login __typename } body"
    aliases = " ".join(f"p{n}: pullRequest(number: {n}) {{ {fields} }}" for n in numbers)
    query = f'query {{ repository(owner: "jupyterlab", name: "jupyterlab") {{ {aliases} }} }}'
    out = subprocess.run(["gh", "api", "graphql", "-f", f"query={query}"], capture_output=True, text=True, check=True)
    return json.loads(out.stdout)["data"]["repository"]


def ai_answer(body):
    """Return 'yes', 'no', 'blank' (left unfilled), 'other' (free text) or 'none' (no AI section)."""
    if not body:
        return "none"
    for line in body.splitlines():
        if "generated by AI" in line:
            head = line.split("Some or all")[0]
            # an answer typed inside the placeholder comment still counts
            head = re.sub(r"<!--\s*(YES|NO)\s*-->", r"\1", head, flags=re.I)
            head = re.sub(r"<!--.*?-->", "", head)
            text = re.sub(r"[*\-:\s\[\]`_]", "", head).upper()
            if text.startswith("YES"):
                return "yes"
            if text.startswith("NO"):
                return "no"
            return "blank"
    # free-form answer under an "AI usage" heading
    m = re.search(r"^#+\s*AI usage\s*$\n+(.+)", body, re.I | re.M)
    if m:
        line = m.group(1)
        first = re.sub(r"[*\-:\s`_>.']", "", line).upper()
        if first.startswith(("NONE", "N/A", "NA", "IMAHUMAN", "NOAI")) or first == "NO" or first.startswith("NO,"):
            return "no"
        if first.startswith("YES") or re.search(r"<!--\s*YES or NO\s*-->\**:\s*YES", line, re.I):
            return "yes"
        return "other"
    return "none"


# Free-text answers read by hand (see sources/release-stats/README.md).
OVERRIDES = {
    18961: "yes",  # "Some but mostly on autocomplete level"
    18908: "yes",  # "Used Claude for final commit ..."
    18901: "yes",  # "... iterated with Claude ..."
    18610: "yes",  # "Some parts of this PR were assisted by AI tools."
    18657: "no",   # "Minimal checks with copilot." (no generated content)
}


def tools_used(body):
    m = re.search(r"AI tools and models used:\s*(.*)", body or "")
    if not m:
        return ""
    text = re.sub(r"<!--.*?-->", "", m.group(1)).strip()
    return "" if text.upper() in {"", "N/A", "NA", "NONE", "-"} else text


def main():
    prs = changelog_prs(VERSION)
    cache = OUT / f"raw-{VERSION}.json"
    data = json.loads(cache.read_text()) if cache.exists() else {}
    numbers = [p["number"] for p in prs if f"p{p['number']}" not in data]
    for i in range(0, len(numbers), 50):
        data.update(fetch(numbers[i:i + 50]))
    OUT.mkdir(parents=True, exist_ok=True)
    cache.write_text(json.dumps(data))
    rows = []
    for p in prs:
        d = data[f"p{p['number']}"]
        author = d["author"] or {}
        rows.append({
            **p,
            "title": d["title"],
            "author": author.get("login"),
            "bot": author.get("__typename") == "Bot" or (author.get("login") or "").endswith("[bot]"),
            "created": d["createdAt"],
            "merged": d["mergedAt"],
            "ai": OVERRIDES.get(p["number"], ai_answer(d["body"])),
            "tools": tools_used(d["body"]),
        })
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"prs-{VERSION}.json").write_text(json.dumps(rows, indent=1))

    humans = [r for r in rows if not r["bot"]]
    after = [r for r in humans if r["created"] >= TEMPLATE_DATE]
    answered = [r for r in humans if r["ai"] in ("yes", "no")]
    others = [r for r in humans if r["ai"] == "other"]
    print(f"{VERSION}: {len(rows)} PRs in the changelog, {len(rows) - len(humans)} by bots, {len(humans)} by people")
    print(f"opened on or after {TEMPLATE_DATE}: {len(after)}")
    print("answers (people):", dict(Counter(r["ai"] for r in humans)))
    print("answers (opened after template):", dict(Counter(r["ai"] for r in after)))
    yes = sum(r["ai"] == "yes" for r in answered)
    print(f"answered: {len(answered)}, yes: {yes} ({100 * yes / max(1, len(answered)):.0f}%)")
    print("free-text answers:", [(r["number"], r["author"]) for r in others])
    by_cat = Counter()
    for r in answered:
        by_cat[(r["category"], r["ai"])] += 1
    for cat in sorted({c for c, _ in by_cat}):
        print(f"  {cat}: yes {by_cat[(cat, 'yes')]}, no {by_cat[(cat, 'no')]}")
    tools = Counter()
    for r in answered:
        if r["ai"] == "yes" and r["tools"]:
            for name in ["Claude", "Copilot", "Cursor", "ChatGPT", "GPT", "Codex", "Gemini", "Windsurf", "Kiro", "Jupyternaut"]:
                if name.lower() in r["tools"].lower():
                    tools[name] += 1
    print("tools named in yes answers:", dict(tools.most_common()))


if __name__ == "__main__":
    main()
